<?php

namespace Container6M6H9GB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QCkNFs2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qCkNFs2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qCkNFs2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\DiscController::delete' => ['privates', '.service_locator.6fwEAbD', 'get_ServiceLocator_6fwEAbDService', true],
            'App\\Controller\\DiscController::edit' => ['privates', '.service_locator.6fwEAbD', 'get_ServiceLocator_6fwEAbDService', true],
            'App\\Controller\\DiscController::index' => ['privates', '.service_locator.H4WH5pQ', 'get_ServiceLocator_H4WH5pQService', true],
            'App\\Controller\\DiscController::new' => ['privates', '.service_locator.H4WH5pQ', 'get_ServiceLocator_H4WH5pQService', true],
            'App\\Controller\\DiscController::show' => ['privates', '.service_locator.v2KlY93', 'get_ServiceLocator_V2KlY93Service', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.mzjt3rI', 'get_ServiceLocator_Mzjt3rIService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\DiscController:delete' => ['privates', '.service_locator.6fwEAbD', 'get_ServiceLocator_6fwEAbDService', true],
            'App\\Controller\\DiscController:edit' => ['privates', '.service_locator.6fwEAbD', 'get_ServiceLocator_6fwEAbDService', true],
            'App\\Controller\\DiscController:index' => ['privates', '.service_locator.H4WH5pQ', 'get_ServiceLocator_H4WH5pQService', true],
            'App\\Controller\\DiscController:new' => ['privates', '.service_locator.H4WH5pQ', 'get_ServiceLocator_H4WH5pQService', true],
            'App\\Controller\\DiscController:show' => ['privates', '.service_locator.v2KlY93', 'get_ServiceLocator_V2KlY93Service', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.mzjt3rI', 'get_ServiceLocator_Mzjt3rIService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\DiscController::delete' => '?',
            'App\\Controller\\DiscController::edit' => '?',
            'App\\Controller\\DiscController::index' => '?',
            'App\\Controller\\DiscController::new' => '?',
            'App\\Controller\\DiscController::show' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\DiscController:delete' => '?',
            'App\\Controller\\DiscController:edit' => '?',
            'App\\Controller\\DiscController:index' => '?',
            'App\\Controller\\DiscController:new' => '?',
            'App\\Controller\\DiscController:show' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
