<?php

namespace Container6M6H9GB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiscTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\DiscType' shared autowired service.
     *
     * @return \App\Form\DiscType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/DiscType.php';

        return $container->privates['App\\Form\\DiscType'] = new \App\Form\DiscType();
    }
}
