<?php

namespace ContainerX45LbEw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H4WH5pQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H4WH5pQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H4WH5pQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'discRepository' => ['privates', 'App\\Repository\\DiscRepository', 'getDiscRepositoryService', true],
        ], [
            'discRepository' => 'App\\Repository\\DiscRepository',
        ]);
    }
}
