<?php

namespace ContainerYboLW0p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDisc2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.v2KlY93.App\Entity\Disc' shared service.
     *
     * @return \App\Entity\Disc
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.v2KlY93": it references class "App\\Entity\\Disc" but no such service exists.');
    }
}
