<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVy8lUvd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVy8lUvd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVy8lUvd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVy8lUvd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVy8lUvd\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vy8lUvd',
    'container.build_id' => '0dfa0fd8',
    'container.build_time' => 1654607179,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVy8lUvd');
